### ISSUE TITLE
MyFirstVsgApplication build fails on MacOS 10.15.5 / Xcode 11.6

### ISSUE THREAD

**Issue by rainergericke** [vsg-dev/MyFirstVsgApplication#1]
Hello, 

I tried to build MyFirstVsgApplication an the Mac. Configuration went well but the build failed due to this problem:

Scanning dependencies of target myfirstvsgapplication
[ 50%] Building CXX object CMakeFiles/myfirstvsgapplication.dir/src/main.cpp.o
/Users/rainerge/Soft/Entwicklung/VSG/MyFirstVsgApplication/src/main.cpp:113:70: error: too many arguments to function call, expected
      single argument 'commandGraphs', have 2 arguments
    viewer->assignRecordAndSubmitTaskAndPresentation({commandGraph}, databasePager);
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 ^~~~~~~~~~~~~
/Users/rainerge/Soft/Packs/VSG/include/vsg/viewer/Viewer.h:96:9: note: 'assignRecordAndSubmitTaskAndPresentation' declared here
        void assignRecordAndSubmitTaskAndPresentation(CommandGraphs commandGraphs);
        ^
1 error generated.
make[2]: *** [CMakeFiles/myfirstvsgapplication.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/myfirstvsgapplication.dir/all] Error 2
make: *** [all] Error 2

When I removed the second argument 'databasePager' from line 113 the build completes. I could load the model 'lz.vsgt' but loading 'glider.vsgt' led to a coredump.

Best

Rainer

**Comment by robertosfield** [comment]
HI Rainer,

I simplified the Viewer setup so it no longer needs the DatabasePager to be
passed. I updated MyFirstVsgApplication but didn't merge with master so
I've gone ahead an merged so could you please update to latest VSG,
(vsgXchange if you are using it) and MyFirstVsgApplication and rebuild,
this should fix build and load issues.

Robert.

**Comment by rainergericke** [comment]
Hi Robert,

Thanks for the quick reaction. I did what you proposed and everything worked well.

Best

Rainer

**Comment by robertosfield** [comment]
On Thu, 16 Jul 2020 at 14:57, rainergericke <notifications@github.com>
wrote:

> Thanks for the quick reaction. I did what you proposed and everything
> worked well.
>

Good to hear the problems are resolved.
