### ISSUE TITLE
Incorrect rendering of glider.vsgt

### ISSUE THREAD

**Issue by kwahoo2** [vsg-dev/MyFirstVsgApplication#5]
Hello,

It seems that the glider example does not render correctly on my machine. This is what I see after running bin/myfirstvsgapplication models/glider.vsgt: 
![vsg glider](https://i.imgur.com/2RGRLBa.png)

For comparison there is glider from OSG repository, opened in osgviewer:
![osgviewer glider](https://i.imgur.com/9odFhEh.png)

Some faces are missing, depth/occlusion test as well. If I convert glider.osgt to vsgt running vsgconv, the picture will look as the first one. This is reproducible for other examples from the OSG repository.

I run Vulkan on Radeon 5700XT/RADV/Ubuntu 21.04

```Device Groups:
==============
Group 0:
        Properties:
                physicalDevices: count = 1
                        AMD RADV NAVI10 (LLVM 10.0.0) (ID: 0)
                subsetAllocation = 0

        Present Capabilities:
                AMD RADV NAVI10 (LLVM 10.0.0) (ID: 0):
                        Can present images from the following devices: count = 1
                                AMD RADV NAVI10 (LLVM 10.0.0) (ID: 0)
                Present modes: count = 1
                        DEVICE_GROUP_PRESENT_MODE_LOCAL_BIT_KHR


Device Properties and Extensions:
=================================
GPU0:
VkPhysicalDeviceProperties:
---------------------------
        apiVersion     = 4198507 (1.1.107)
        driverVersion  = 80097379 (0x4c63063)
        vendorID       = 0x1002
        deviceID       = 0x731f
        deviceType     = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName     = AMD RADV NAVI10 (LLVM 10.0.0)
```

**Comment by robertosfield** [comment]
I haven't seen issues like this on my Xubuntu 18.04, Kubuntu 20.94 and
Ubuntu 21.04, with NVidia hardware/drivers.

I haven't got an AMD card to test against so will need you to do some more
testing to see if we can find out what is going wrong - either a setting
issue with the VSG or a bug in the driver.

Could you make sure Vulkan debug and api layers are set up (see VulkanSDK
docs for details) and run vsgviewer with -d command line option to enable
the debug layer, and -a to generate the api calls.  This debug data will be
written by the Vulkan layer to the console.

If you have built vsgXchange with OpenSceneGraph support, and have the
OpenSceneGraoh-Data on your path you should be able to do:

   vsgviewer glider.osgt -d  // enb
   vsgviewer dumptruck.osgt -a

The -a api output will include the debug output, but you'll have to go hunt
for the errors as there are many Vulkan calls that the VSG has to do just
to create all the required Vulkan objects.

--

As a general note, the screenshot looks like depth write/depth test might
be not working as intended rather than mesh being missing.

>

**Comment by kwahoo2** [comment]
opening osgt files vsgviewer crashes, 
vsgviewer glider.osgt -d log:
[glider.osgt.log](https://github.com/vsg-dev/MyFirstVsgApplication/files/6566038/glider.osgt.log)
vsgviewer glider.vsgt -d:
[glider.vsgt.log](https://github.com/vsg-dev/MyFirstVsgApplication/files/6566053/glider.vsgt.log)
vsgviewer glider.osgt -a:
[glider.osgt.api.log](https://github.com/vsg-dev/MyFirstVsgApplication/files/6566049/glider.osgt.api.log)
vsgviewer glider.vsgt -a:
[glider.vsgt.api.log](https://github.com/vsg-dev/MyFirstVsgApplication/files/6566061/glider.vsgt.api.log)

This does seem to be interesting part
```
VUID-VkSubpassDescription-pDepthStencilAttachment-02650(ERROR / SPEC): msgNum: -996339680 - Validation Error: [ VUID-VkSubpassDescription-pDepthStencilAttachment-02650 ] Object 0: handle = 0x564f30772010, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xc49d1020 | vkCreateRenderPass(): Depth Stencil pSubpasses[0].pDepthStencilAttachment format (VK_FORMAT_D24_UNORM_S8_UINT) does not contain VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT. The Vulkan spec states: If pDepthStencilAttachment is not NULL and the attachment is not VK_ATTACHMENT_UNUSED then it must have an image format whose potential format features contain VK_FORMAT_FEATURE_DEPTH_STENCIL_ATTACHMENT_BIT (https://vulkan.lunarg.com/doc/view/1.2.176.1/linux/1.2-extensions/vkspec.html#VUID-VkSubpassDescription-pDepthStencilAttachment-02650)
```

**Comment by robertosfield** [comment]
Thanks for the logs.  I don't see these errors when running on NVidia, I do see a these errors with vsgviewer glider.osgt -d:

**Comment by kwahoo2** [comment]
> could you try it out and see what changes if any you see on your system:
> 
> #8e5dcebd7a093b3885d05332108201610362170d

I see no difference. 
But, it seems (at least partially) it is a driver issue. I ran the viewer using lavapipe (CPU-based Vulkan)
```
VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/lvp_icd.x86_64.json vsgviewer glider.vsgt
```
![lavapipevsgviewer](https://user-images.githubusercontent.com/3474114/120223617-28055400-c242-11eb-8f31-937ca7d7f4f7.png)

And that is full vsgviewer -d output
```
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55b937e1fe70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.4 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).
    Objects: 1
        [0] 0x55b937e1fe70, type: 3, name: NULL
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x55b937e1fe70, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.4 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).
    Objects: 1
        [0] 0x55b937e1fe70, type: 3, name: NULL
```

I'm going to fill an issue on Mesa tracker for that.

**Comment by robertosfield** [comment]
The Spriv error might not be a Vulkan issue, it could be an issue with the
VSG's settings of SPIR-V/Vulkan versions during calls to glsLang,  I will
need to look at the glsLang more closely.

**Comment by kwahoo2** [comment]
According to Mesa devs depth error is caused by missing 24-bit depth buffer support in RADV.

> 24-bit depth buffers aren't supported by RADV and won't be because no compression. I recommend you to use a D32S8 instead.

https://gitlab.freedesktop.org/mesa/mesa/-/issues/4864#note_940488

**Comment by robertosfield** [comment]
Thanks for chasing things up with the Mesa devs, we can set the depthFormat
of the window vis WindowTraits, from include/vsg/viewer/WindowTraits.h:

        VkFormat depthFormat = VK_FORMAT_D24_UNORM_S8_UINT;
//VK_FORMAT_D32_SFLOAT; // VK_FORMAT_D32_SFLOAT_S8_UINT,
VK_FORMAT_D24_SFLOAT_S8_UINT

The vsgviewer example has the line:

        if (arguments.read("--d32")) windowTraits->depthFormat =
VK_FORMAT_D32_SFLOAT;

So could you try:

       vsgviewer glider.osgt --d32

This works OK on my NIvida/Ubuntu 21.04 machine.  I don't know whether this
is portable across all systems though.  It may be possible to test for
requested support and if it fails come up with a fallback scheme for trying
other related formats.

**Comment by kwahoo2** [comment]
`vsgviewer glider.osgt --d32`
Does not crash anymore and fixes the depth format error.

`vsgviewer glider.vsgt --d32`
Fixes the depth format error.

3D view and debug output are now identical with Lavapipe implementation.

**Comment by robertosfield** [comment]
On Tue, 1 Jun 2021 at 16:24, kwahoo2 ***@***.***> wrote:

> vsgviewer glider.osgt --d32
> Does not crash anymore and fixes the depth format error.
>
> vsgviewer glider.vsgt --d32
> Fixes the depth format error.
>
> 3D view and debug output are now identical with Lavapipe implementation.
>

That's great to hear.  I'll need to figure out what to do with defaults and
a fallback mechanism.

I'm currently working on resolving the SPIR-V version issue, once this is
fixed I'll return to the depthFormat issue.

**Comment by robertosfield** [comment]
I have finished my work added shader compilation controls to the VulkanSceneGraph which should resolve the SPIR-V version issue so the hack of removing the the shader->setEnvTarget(glslang::EShTargetSpv, glslang::EShTargetSpv_1_4);  call will no longer required, VSG master should be sufficient:

[https://github.com/vsg-dev/VulkanSceneGraph/pull/286](https://github.com/vsg-dev/VulkanSceneGraph/pull/286)

I still need to resolve the WindowTraits::depthFormat default setting.

**Comment by kwahoo2** [comment]
Nothing changed for me unforunately.
```
vsgviewer glider.vsgt -d --d32
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x5634ddce85a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.4 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).
    Objects: 1
        [0] 0x5634ddce85a0, type: 3, name: NULL
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x5634ddce85a0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Invalid SPIR-V binary version 1.4 for target environment SPIR-V 1.0 (under Vulkan 1.0 semantics).
    Objects: 1
        [0] 0x5634ddce85a0, type: 3, name: NULL
```
Things I did:

- Pulled VulkanSceneGraph 4f3d1c78, recompiled and reinstalled (make clean, make, make install).
- Recompiled and reinstalled vsgXchange, vsgExamples and MyFirstVSGApplictation (no new commits here)

**Comment by robertosfield** [comment]
I think the problem is that glider.vsgt has SPIR-V compiled in with EShTargetSpv_1_4. Try vsgviewer glider.osgt

**Comment by kwahoo2** [comment]
DepthFormat issue is fixed now. 
`vsgviewer glider.osgt -d`
and 
`vsgviewer glider.osgt -a`

does not show any errors now. Also glider.vsgt after recreating with vsgconv does not show errors. But the model still looks that way https://user-images.githubusercontent.com/3474114/120223617-28055400-c242-11eb-8f31-937ca7d7f4f7.png

Api output:
`vsgviewer glider.osgt -a`
[gliderapilast.log](https://github.com/vsg-dev/MyFirstVsgApplication/files/6586275/gliderapilast.log)

**Comment by robertosfield** [comment]
Thanks for testing.  

The flat shading is due to the original glider.osgt not enabling lighting, but the OSG by default enables it, if it didn't the OSG would be flat shaded as well.  Try dumptruck.osgt, it explictly enables lighting in the shader and the vsgXchange OSG loader then knows to enable lighting in the shaders it creates.

**Comment by kwahoo2** [comment]
Ok, the dumptruck lighting looks ok. Than you for your help. Closing the issue.
