### ISSUE TITLE
Uncaught exception on macOS 12.6 (arm64) / VulkanSDK 1.3.231.1

### ISSUE THREAD

**Issue by jdf-id-au** [vsg-dev/MyFirstVsgApplication#9]
Thanks for this example project, I'm excited to get it working.

I was able to build it (with lots of warnings of the form _ld: warning: object file (/usr/local/lib/libvsgd.a(Camera.o)) was built for newer macOS version (12.3) than being linked (12.0)_), but when I tried to run it with `./bin/myfirstvsgapplication models/lz.vsgt`, I got 

```
libc++abi: terminating with uncaught exception of type vsg::Exception
fish: Job 1, './bin/myfirstvsgapplication mod…' terminated by signal SIGABRT (Abort)
```

I think it comes from [this line](https://github.com/vsg-dev/MyFirstVsgApplication/blob/master/src/main.cpp#L99).

I'm not very familiar with C++. Is there anything I can do to help work out why the exception is being thrown?

**Comment by robertosfield** [comment]
I don't personally have a macOS system so test it our myself.   Unfortunately the application is very simple, to keep it simple there isn't a try/catch block around the code so isn't able to report the details of the exception.

The vsgviewer example in vsgExamples does have try/catch block so should report more information. Have you tried out vsgExamples?  You can use the same model and command line parameters with vsgviewer and should provide the same visuals as they have much in common, just MyFirstVsgApplication is more cut down.

**Comment by jdf-id-au** [comment]
Thank you! This time:

```
./bin/vsgviewer ../MyFirstVsgApplication/models/lz.vsgt 
[Exception] - Error: vsg::Instance::create(...) failed to create VkInstance. result = -9
```
I'm trying to find what the meaning of -9 is.

**Comment by robertosfield** [comment]
On Sat, 12 Nov 2022 at 20:26, Jeremy Field ***@***.***> wrote:

> Thank you! This time:
>
> ./bin/vsgviewer ../MyFirstVsgApplication/models/lz.vsgt
> [Exception] - Error: vsg::Instance::create(...) failed to create VkInstance. result = -9
>
> I'm trying to find what the meaning of -9 is.
>
It's a VkResult value:
https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkResult.html

-9 corresponds to VK_ERROR_INCOMPATIBLE_DRIVER.

I'm afraid I can't help with how to resolve that as it's a macOS specific
issue relating to the driver.  There are members of vsg-users who use macOS
so perhaps joining vsg-users googlegroup or posting a note to the
VulkanSceneGraph Discussion pages on github might pull in some helpful
advice on setting up Vulkan on macOS.
